// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// Loads environment variables from .env file
import 'dotenv/config';

// Ref: https://www.prisma.io/docs/prisma-orm/quickstart/mysql
// Imports Prisma's config helper
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Reads the database connection string from the DATABASE_URL env variable
    url: env('DATABASE_URL'),
  },
});
